#!/usr/bin/bash
echo -n 'Do you want to clean out the temp files? Y/N  ' 	# asks for user input 
read d							# records the what the user entered to the d varible 
echo

if [ $d == 'Y' ]; then #if the user enters yes, it will  delete all the text files in the folder.
        rm -v TempFiles/*.txt
	#echo
	#echo "ops, readme deleated ... regenerating."
	#echo
	#sleep 1
	#./ReadmeRemaker
else
	echo 'no files deleted'
	echo
fi

