#!/usr/bin/bash
# a silly script that, creates a garbage file, cleans the file, then sorts the output
#

./DeleteUtil

echo
echo -n "Enter S for Silent Mode, enter any key other key for Verbose Mode: "
read x
#rm -v TempFiles/Value.txt
echo $x > TempFiles/Value.txt #Submitting User input to a file to be read back by the other sub programs. This will set them into either silent or verbose mode.
	
if [ $x = 'S' ]; then #If the user entered S, then it will run the all the sub programs in silent mode.
	echo
	./GarbageGen #Runs the GarbageGen module, creates a garbage file.
	sleep 1
	./FileCleaner #Runs the FileCleaner module, cleans the file and preps it for the sorting module.
	sleep 1
	./FileSorter #Runs the FileSorter Module, sorts the contents of the file in alphabetical order. 
	sleep 1
	echo 'Output file is TempFiles/Sorted.txt'
	sleep 1
	./FileAnalyser


else
	# creating garbage file
	echo
	echo 'creating silly garbage file'
	echo
	sleep 4
	#running GarbageGen
		./GarbageGen
	# shows garbage file
	sleep 4
	more TempFiles/Junk.txt # displying the output of GarbageGen
	# running FileCleaner to clean the file
	echo
	echo 'Cleaning GarbageFile'
	echo
	sleep 4
	echo
	#running file cleaner
	./FileCleaner
	echo
	sleep 4
	more TempFiles/Clean.txt #Displaying the output of FileCleaner
	# sorting garbage file
	echo
	echo 'Sorting The File'
	echo
	sleep 4
	echo
	./FileSorter
	sleep 4
	echo
	more TempFiles/Sorted.txt #Displaying the output of FileSorter, the final output of this program
	echo
	sleep 4
	echo 'script complete'
	echo 'Output file is TempFiles/Sorted.txt'
	sleep 1
	./FileAnalyser

fi
