#!/usr/bin/bash
# This script prompts the user to enter a number, checks if it’s even, and prints a message accordingly.
# Prompt the user to enter a number
# Check if the entered number is even
   
y=$(cat Value.txt) 

if [ $y = 'S' ]; then
      echo “Silent Mode”
else
      echo "Verbose Mode"
fi


