#!/usr/bin/bash
#program that cleans up Junk.txt

c=$(cat TempFiles/Value.txt) #reads the value of Value.txt, determines if the program runs in silent or verbose mode.

if [ $c = 'S' ] || [ $c = 's' ]; then #silent mode
	more TempFiles/Junk.txt | tr '{},' ' ' | tr -d ' ' | tr '-' ' ' | tr -s ' ' > TempFiles/Clean.txt 	
											# removes the junk chars, deletes spaces
											# replaces the dashes with spaces
											# removes extra spaces
											# records the output to Clean.txt
elif [ $c = 'V' ] || [ $c = 'v' ]; then
	echo
	echo 'Cleaning Junk.txt...'
	echo
	echo 'Removing random chars...'
	echo
	echo 'Creating Clean.txt...'
	echo
	echo 'Cleaning File...'
	echo
	more TempFiles/Junk.txt | tr '{},' ' ' | tr -d ' ' | tr '-' ' ' | tr -s ' ' > TempFiles/Clean.txt
	echo 'script complete'
	echo

else
	echo $c ": Expected S/s or V/v"
fi
