#!/usr/bin/bash

#
# Author: cyber-yoda
# 
# Description: generates a file full of random data
#


# set envrioment var from Value.txt

a=$(cat TempFiles/Value.txt) # reads user input

if [ $a = 'S' ] || [ $a = 's' ]; then # silent mode
	touch TempFiles/Junk.txt # creates Junk.txt if it does not exist.
	for a in {1..9}
	do
	#echo >> TempFiles/Junk.txt
	./RandomGen >> TempFiles/Junk.txt # runs the random gen command 9 times and appends the results to Junk.txt
	echo >> TempFiles/Junk.txt
	done
elif [ $a = 'V' ] || [ $a = 'v' ]; then
	printf
	printf 'Creating an empty file: Junk.txt, or updating the time stamp if the file already exists...'
	printf
	touch TempFiles/Junk.txt
	printf
	printf 'Appending junk to file...'
	printf
	#starting for loop
	for a in {1..9}
	do
		#echo >> TempFiles/Junk.txt
		./RandomGen >> TempFiles/Junk.txt
		echo >> TempFiles/Junk.txt
	done
	printf
	printf 'Script complete'
	printf

else

	printf $a ": Expected S/s or V/v"

fi
	


